# Generated by Django 4.2.1 on 2023-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="matrix_room_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="role",
            field=models.CharField(
                choices=[("DAILY_DIGEST", "DAILY_DIGEST")], max_length=64
            ),
        ),
    ]
