# Generated by Django 4.2.1 on 2024-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_update_empty_created_by_and_updated_by_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="group",
            name="updated_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="updated_by",
            field=models.UUIDField(),
        ),
    ]
