# Generated by Django 4.2.1 on 2024-04-09 09:04

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0032_person_metadata"),
        (
            "notifications",
            "0004_alter_group_created_by_alter_group_updated_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SenderID",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="Date after which the sender is invalid."
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="Date from which the sender is valid."
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("PROMOTION", "PROMOTION"),
                            ("TRANSACTION", "TRANSACTION"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
