# Generated by Django 4.2.1 on 2024-04-19 13:28

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0032_person_metadata"),
        ("notifications", "0005_senderid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMS",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("message", models.CharField()),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20), size=None
                    ),
                ),
                ("intention", models.CharField(max_length=20)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("FAILED", "FAILED"),
                            ("SENT", "SENT"),
                            ("REJECTED", "REJECTED"),
                            ("DELIVERED", "DELIVERED"),
                            ("UNDELIVERED", "UNDELIVERED"),
                            ("RECEIVED", "RECEIVED"),
                        ],
                        default="QUEUED",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sil_comms_sms_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the SMS assigned on SIL Comms",
                        null=True,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="notifications.senderid",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
