# Generated by Django 4.2.1 on 2024-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_sms"),
    ]

    operations = [
        migrations.AddField(
            model_name="sms",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sms",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QUEUED", "QUEUED"),
                    ("FAILED", "FAILED"),
                    ("SENT", "SENT"),
                    ("REJECTED", "REJECTED"),
                    ("DELIVERED", "DELIVERED"),
                    ("UNDELIVERED", "UNDELIVERED"),
                    ("RECEIVED", "RECEIVED"),
                    ("RETRIED", "RETRIED"),
                ],
                default="QUEUED",
                max_length=50,
                null=True,
            ),
        ),
    ]
