# Generated by Django 4.2.1 on 2024-07-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0007_sms_failure_reason_alter_sms_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sms",
            name="intention",
            field=models.CharField(max_length=100),
        ),
    ]
