# Generated by Django 4.2.1 on 2024-07-16 14:17

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0038_alter_practitioner_qualification"),
        ("notifications", "0008_alter_sms_intention"),
    ]

    operations = [
        migrations.CreateModel(
            name="USSDCode",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("ussd_code", models.CharField(max_length=255, unique=True)),
                (
                    "gateway",
                    models.CharField(
                        choices=[("SAFARICOM", "SAFARICOM")], max_length=50
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PREPAID", "Pre-Paid USSD Code"),
                            ("POSTPAID", "Post-Paid USSD Code"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
