# Generated by Django 4.2.1 on 2024-09-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_ussdcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="sms",
            name="delivery_type",
            field=models.CharField(
                choices=[("OUTBOUND", "OUTBOUND"), ("INBOUND", "INBOUND")],
                default="OUTBOUND",
                help_text="Indicates whether an SMS is inbound or outbound",
                max_length=10,
            ),
        ),
    ]
