# Generated by Django 4.2.1 on 2024-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_ussdcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="senderid",
            name="available_from",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="senderid",
            name="available_to",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
