# Generated by Django 4.2.1 on 2024-09-21 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_senderid_available_from_senderid_available_to"),
        ("notifications", "0010_sms_delivery_type"),
    ]

    operations = []
