# Generated by Django 4.2.1 on 2024-09-23 08:47

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0047_alter_consent_options_alter_consent_unique_together"),
        ("notifications", "0011_merge_20240921_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="senderid",
            name="classification",
            field=models.CharField(
                choices=[
                    ("SENDER_ID", "A BulkSMS SenderID"),
                    ("INTERACTIVE_SHORTCODE", "An interactive ShortCode"),
                ],
                default="SENDER_ID",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="SMSLogReport",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "process_state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Report in pending state"),
                            ("IN_PROGRESS", "Report in progress state"),
                            ("COMPLETE", "Report in complete state"),
                            ("FAILED", "Report in failed state"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "report_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="common.attachment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
