# Generated by Django 4.2.1 on 2023-09-15 09:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "scheduling",
            "0001_squashed_0015_alter_appointment_priority_alter_schedule_specialty",
        ),
        ("common", "0001_squashed_0016_instancehistory"),
        (
            "patients",
            "0001_squashed_0014_remove_patient_registration_complete_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("TRIAGE", "Triage"),
                            ("CONSULTATION", "Consultation"),
                            ("LAB", "Laboratory"),
                            ("IMAGING", "Imaging"),
                            ("PHARMACY", "Pharmacy"),
                            ("BILLING", "Billing"),
                            ("PROCEDURE", "Procedure"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queue",
                        to="scheduling.schedule",
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("AMB", "Outpatient"),
                            ("IMP", "Inpatient"),
                            ("EMER", "Emergency"),
                            ("FLD", "Field"),
                            ("HH", "Home Health"),
                            ("ACUTE", "Inpatient Acute"),
                            ("NONAC", "Inpatient Non-Acute"),
                            ("OBSENC", "Observation Encounter"),
                            ("PRENC", "Pre-Admission"),
                            ("SS", "Short Stay"),
                            ("VR", "Virtual"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ARRIVED", "Arrived"),
                            ("TRIAGED", "Triaged"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_LEAVE", "On Leave"),
                            ("FINISHED", "Finished"),
                            ("CANCELLED", "Cancelled"),
                            ("ENTERED_IN_ERROR", "Entered In Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "billing_class",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("CREDIT", "Credit")],
                        max_length=10,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="patients.patient",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("URGENT", "Urgent"),
                            ("ASAP", "As Soon As Possible"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="NORMAL",
                        max_length=25,
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "current_queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_visits",
                        to="visits.queue",
                    ),
                ),
                ("visit_number", models.CharField(blank=True, max_length=64)),
                (
                    "episode_of_care_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "post_visit_survey_token",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VisitTransitionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ARRIVED", "Arrived"),
                            ("TRIAGED", "Triaged"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_LEAVE", "On Leave"),
                            ("FINISHED", "Finished"),
                            ("CANCELLED", "Cancelled"),
                            ("ENTERED_IN_ERROR", "Entered In Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_from",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ARRIVED", "Arrived"),
                            ("TRIAGED", "Triaged"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_LEAVE", "On Leave"),
                            ("FINISHED", "Finished"),
                            ("CANCELLED", "Cancelled"),
                            ("ENTERED_IN_ERROR", "Entered In Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_to",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ARRIVED", "Arrived"),
                            ("TRIAGED", "Triaged"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_LEAVE", "On Leave"),
                            ("FINISHED", "Finished"),
                            ("CANCELLED", "Cancelled"),
                            ("ENTERED_IN_ERROR", "Entered In Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_transition_logs",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="QueueTransitionLog",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destination_queues",
                        to="visits.queue",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_queues",
                        to="visits.queue",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queue_transition_logs",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WAITING", "Waiting"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("REVOKED", "Revoked"),
                            ("ENTERED_IN_ERROR", "Entered In Error"),
                        ],
                        default="WAITING",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("URGENT", "Urgent"),
                            ("ASAP", "As Soon As Possible"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="NORMAL",
                        max_length=25,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="visits.queue",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="visits.visit",
                    ),
                ),
                ("encounter_id", models.UUIDField(blank=True, null=True)),
                ("occurrence", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("created", "updated"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("response", models.JSONField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="survey_response",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
