# Generated by Django 4.2.1 on 2023-09-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_squashed_0018_alter_visit_post_visit_survey_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="customer_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="guarantor_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
