# Generated by Django 4.2.1 on 2023-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0019_visit_customer_id_visit_guarantor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="queue_type",
            field=models.CharField(
                choices=[
                    ("TRIAGE", "Triage"),
                    ("CONSULTATION", "Consultation"),
                    ("LAB", "Laboratory"),
                    ("IMAGING", "Imaging"),
                    ("PHARMACY", "Pharmacy"),
                    ("BILLING", "Billing"),
                    ("PROCEDURE", "Procedure"),
                    ("OPTICAL", "Optical"),
                ],
                max_length=50,
            ),
        ),
    ]
