# Generated by Django 4.2.1 on 2023-11-06 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0019_practitioner"),
        ("visits", "0020_alter_queue_queue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="practitioner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="practitioner_queues",
                to="common.practitioner",
            ),
        ),
    ]
