# Generated by Django 4.2.1 on 2023-12-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0021_queue_practitioner"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="queuetransitionlog",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
