# Generated by Django 4.2.1 on 2024-01-19 11:45

from django.conf import settings
from django.db import migrations

from sil_advantage.sil_auth.models import SILUser

# Set network admin as the created_by and updated_by fields
admin_email = settings.SYSTEM_ADMIN_EMAIL
try:
    system_admin = SILUser.objects.get(email=admin_email).id
except:
    system_admin = "fb380243-cf9d-4fb7-a4ae-b119150f65df"

models = [
    "queue",
    "queuetransitionlog",
    "servicerequest",
    "surveyresponse",
    "visit",
    "visittransitionlog",
]


def populate_fields(apps, schema_editor):
    for model_name in models:
        model = apps.get_model("visits", model_name)
        model.objects.filter(created_by__isnull=True).update(created_by=system_admin)
        model.objects.filter(updated_by__isnull=True).update(updated_by=system_admin)


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0022_queue_cluster_id_queuetransitionlog_cluster_id_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_fields),
    ]
