# Generated by Django 4.2.1 on 2024-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0023_update_empty_created_by_and_updated_by_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="queue",
            name="updated_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="queuetransitionlog",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="queuetransitionlog",
            name="updated_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="updated_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="updated_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="visit",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="visit",
            name="updated_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="visittransitionlog",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="visittransitionlog",
            name="updated_by",
            field=models.UUIDField(),
        ),
    ]
