# Generated by Django 4.2.1 on 2024-02-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0024_alter_queue_created_by_alter_queue_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="queue_type",
            field=models.CharField(
                choices=[
                    ("TRIAGE", "Triage"),
                    ("CONSULTATION", "Consultation"),
                    ("LAB", "Laboratory"),
                    ("IMAGING", "Imaging"),
                    ("PHARMACY", "Pharmacy"),
                    ("BILLING", "Billing"),
                    ("PROCEDURE", "Procedure"),
                    ("OPTICAL", "Optical"),
                    ("BREAST CANCER SCREENING", "Breast Cancer Screening"),
                    ("CERVICAL CANCER SCREENING", "Cervical Cancer Screening"),
                ],
                max_length=50,
            ),
        ),
    ]
