# Generated by Django 4.2.1 on 2024-02-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0025_alter_queue_queue_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("WAITING", "Waiting"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("ON_HOLD", "On Hold"),
                    ("REVOKED", "Revoked"),
                    ("ENTERED_IN_ERROR", "Entered In Error"),
                ],
                default="WAITING",
                max_length=50,
            ),
        ),
    ]
