# Generated by Django 4.2.1 on 2024-03-08 10:55

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0031_merge_20240305_1131"),
        ("visits", "0026_alter_servicerequest_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitDispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("DISPATCHED", "Dispatched"),
                            ("PAID", "Paid"),
                            ("REJECTED", "Rejected"),
                            ("REDISPATCHED", "Redispatched"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("date_added", models.DateField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="scheme_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VisitDispatchTransitionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "status_from",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("DISPATCHED", "Dispatched"),
                            ("PAID", "Paid"),
                            ("REJECTED", "Rejected"),
                            ("REDISPATCHED", "Redispatched"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_to",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("DISPATCHED", "Dispatched"),
                            ("PAID", "Paid"),
                            ("REJECTED", "Rejected"),
                            ("REDISPATCHED", "Redispatched"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "visit_dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_dispatch_transition_logs",
                        to="visits.visitdispatch",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="visitdispatch",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="visits.visit"
            ),
        ),
    ]
