# Generated by Django 4.2.1 on 2024-03-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practitioners", "0002_alter_practitioner_qualification"),
        ("visits", "0027_visitdispatch_visit_scheme_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="practitioner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="practitioner_queues",
                to="practitioners.practitioner",
            ),
        ),
    ]
