# Generated by Django 4.2.1 on 2024-03-21 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0028_alter_queue_practitioner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="scheme_id",
            new_name="patient_cover",
        ),
    ]
