# Generated by Django 4.2 on 2023-08-23 10:08

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models

import sil_advantage.common.models.mixins
import sil_advantage.integrations.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "system",
                    models.CharField(
                        choices=[("GOOGLE_DRIVE", "GOOGLE_DRIVE")],
                        max_length=64,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PATIENT_RECORDS_UPLOAD", "PATIENT_RECORDS_UPLOAD"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "config",
                    sil_advantage.integrations.models.EncryptedJsonField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "organisations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
