.PHONY: all
all: lint type_check test

.PHONY: test
test:
	pytest tests/

.PHONY: test_incr
test_incr:
	pytest tests/ --testmon --no-cov -n 0

.PHONY: lint
lint:
	flake8 .
	./commit_lint.sh

.PHONY: format
format:
	isort .
	black .

.PHONY: type_check
type_check:
	mypy sil_advantage/

.PHONY: changelog
changelog:
	git-changelog --style conventional \
		--sections feat,fix,revert,refactor,perf,build,ci,deps,docs,style,test \
		--template path:CHANGELOG.md.jinja \
		--bump-latest \
		-o CHANGELOG.md

.PHONY: package
package:
	python3 setup.py sdist upload -r slade

.PHONY: clean
clean:
	rm -rf .pytest_cache .tox dist .coverage sil_advantage.egg-info build celerybeat-schedule .mypy_cache
	py3clean .

.PHONY: help
help:
	@echo "Usage:"
	@echo "  make"
	@echo "  	Run flake8 & pytest"
	@echo "  make test"
	@echo "  	Run pytest & output coverage results"
	@echo "  make test_incr"
	@echo "  	Run only tests with recent changes (speedup!)"
	@echo "  make lint"
	@echo "  	Run the flake8 linter"
	@echo "  make format"
	@echo "  	Auto-format Python code"
	@echo "  make type_check"
	@echo "  	Run static type checking with mypy"
	@echo "  make changelog"
	@echo "  	Update the CHANGELOG"
	@echo "  make package"
	@echo "  	Build the package and upload it to SIL's Pip Registry"
	@echo "  make clean"
	@echo "  	Remove autogenerated files like __py_cache__"
	@echo "  make help"
	@echo "  	Display usage information"
