[tox]
envlist = tests, docs


[pytest]
DJANGO_SETTINGS_MODULE = tests.config.settings
norecursedirs =
  venv,
  build,
  env,
  bin,
  .cache,
  .tox,
  .mypy_cache,
  deploy,
  docs,
  profiling,
  requirements,
  .git,
  *.egg-info,
  node_modules,
testpaths = tests
addopts = --cov=sil_advantage --durations=25 -n auto -v
minversion = 3.11


[flake8]
exclude =
  migrations,
  dist,
  env,
  venv,
  build,
  .tox,
  .cache,
  .git,
  sil_advantage/__init__.py
max-line-length = 80
max-complexity = 10
# Use Bugbear's B950 "Line too long" error
# It's a pragmatic equivalent of pycodestyle's E501
extend-ignore = E501
extend-select = B950
docstring-convention = google
show-source = true


[coverage:run]
branch = True
source = sil_advantage
omit =
  sil_advantage/config/*
  sil_advantage/**/migrations/*

[coverage:report]
fail_under = 100
show_missing = True


[tool:isort]
profile = black
line_length = 80

[tool:black]
line-length = 80


[mypy]
ignore_missing_imports = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
# override recognizes violations of the Liskov substitution principle
#   it's suppressed here since we depend on external projects
#   like DRF that dictate the superclass definitions,
#   so we can't fix the issues.
disable_error_code =
    override
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

[mypy-*.migrations.*]
ignore_errors = True

[mypy.plugins.django-stubs]
django_settings_module = sil_advantage.config.settings


[testenv]
basepython = python3
allowlist_externals = make
passenv =
    SECRET_KEY
    AWS_KEY_ID
    AWS_SECRET
    DB_NAME
    DB_PORT
    DB_HOST
    DB_USER
    DB_PASS
    GOOGLE_APPLICATION_CREDENTIALS


deps =
  tests: -r requirements/test.txt
  docs: -r requirements/docs.txt

commands =
    tests: make lint
    tests: make type_check
    tests: coverage erase
    tests: make test
    docs: sphinx-build -qWb html -d docs/_build/doctrees docs docs/_build/html --keep-going
