# Generated by Django 4.2.1 on 2023-10-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_squashed_0016_instancehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personcontact",
            name="consent_to_contact_given",
            field=models.BooleanField(default=True),
        ),
    ]
