# Generated by Django 4.2.1 on 2023-10-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0017_alter_personcontact_consent_to_contact_given"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="deceased",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
