# Generated by Django 4.2.1 on 2023-11-01 09:26

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0018_person_deceased"),
    ]

    operations = [
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("OPHTHALMOLOGY", "OPHTHALMOLOGY"),
                            ("INTERNAL MEDICINE", "INTERNAL MEDICINE"),
                            ("CLINICAL PATHOLOGY", "CLINICAL PATHOLOGY"),
                            ("CONSERVATIVE DENTISTRY", "CONSERVATIVE DENTISTRY"),
                            (
                                "GENERAL SURGERY  PLASTIC SURGERY",
                                "GENERAL SURGERY  PLASTIC SURGERY",
                            ),
                            ("MICROBIOLOGY", "MICROBIOLOGY"),
                            ("ORAL PATHOLOGY", "ORAL PATHOLOGY"),
                            (
                                "GENERAL SURGERY  PAEDIATRIC SURGERY",
                                "GENERAL SURGERY  PAEDIATRIC SURGERY",
                            ),
                            (
                                "OBSTETRICS AND GYNAECOLOGY  ONCOLOGY/RADIOTHERAPY",
                                "OBSTETRICS AND GYNAECOLOGY  ONCOLOGY/RADIOTHERAPY",
                            ),
                            ("ENDODONTICS", "ENDODONTICS"),
                            ("RADIOLOGY", "RADIOLOGY"),
                            ("NEPHROLOGY", "NEPHROLOGY"),
                            ("EMERGENCY MEDICINE", "EMERGENCY MEDICINE"),
                            (
                                "EAR  NOSE AND THROAT (ENT SURGERY)",
                                "EAR  NOSE AND THROAT (ENT SURGERY)",
                            ),
                            ("PAEDIATRIC SURGERY", "PAEDIATRIC SURGERY"),
                            ("ONCOLOGY", "ONCOLOGY"),
                            ("PROSTHETIC DENTISTRY", "PROSTHETIC DENTISTRY"),
                            (
                                "OBSTETRICS AND GYNAECOLOGY",
                                "OBSTETRICS AND GYNAECOLOGY",
                            ),
                            ("PUBLIC HEALTH", "PUBLIC HEALTH"),
                            ("OCCUPATIONAL MEDICINE", "OCCUPATIONAL MEDICINE"),
                            ("GENERAL PATHOLOGY", "GENERAL PATHOLOGY"),
                            ("NEUROSURGERY", "NEUROSURGERY"),
                            ("DIABETOLOGY", "DIABETOLOGY"),
                            ("CLINICAL MEDICAL GENETICS", "CLINICAL MEDICAL GENETICS"),
                            ("GENERAL PRACTITIONER", "GENERAL PRACTITIONER"),
                            ("NEUROLOGY", "NEUROLOGY"),
                            ("PROSTHODONTICS", "PROSTHODONTICS"),
                            (
                                "DERMATOLOGY  INTERNAL MEDICINE",
                                "DERMATOLOGY  INTERNAL MEDICINE",
                            ),
                            ("ORTHOPAEDICS", "ORTHOPAEDICS"),
                            ("BIOMATERIALS SCIENCE", "BIOMATERIALS SCIENCE"),
                            (
                                "ORTHOPAEDICS AND TRAUMA SURGERY",
                                "ORTHOPAEDICS AND TRAUMA SURGERY",
                            ),
                            ("RADIOTHERAPY", "RADIOTHERAPY"),
                            ("PAEDIATRIC DENTISTRY", "PAEDIATRIC DENTISTRY"),
                            (
                                "INTERNAL MEDICINE  ONCOLOGY/RADIOTHERAPY",
                                "INTERNAL MEDICINE  ONCOLOGY/RADIOTHERAPY",
                            ),
                            ("ORTHODONTICS", "ORTHODONTICS"),
                            ("RESTORATIVE DENTISTRY", "RESTORATIVE DENTISTRY"),
                            ("GENERAL SURGERY", "GENERAL SURGERY"),
                            (
                                "ORAL AND MAXILLOFACIAL SURGERY",
                                "ORAL AND MAXILLOFACIAL SURGERY",
                            ),
                            ("DERMATOLOGY", "DERMATOLOGY"),
                            ("PSYCHIATRY", "PSYCHIATRY"),
                            (
                                "GENERAL SURGERY  ORTHOPAEDICS",
                                "GENERAL SURGERY  ORTHOPAEDICS",
                            ),
                            ("ORTHOPAEDIC SURGERY", "ORTHOPAEDIC SURGERY"),
                            ("DENTAL RADIOLOGY", "DENTAL RADIOLOGY"),
                            ("PERIODONTOLOGY", "PERIODONTOLOGY"),
                            ("FAMILY MEDICINE", "FAMILY MEDICINE"),
                            ("PALLIATIVE MEDICINE", "PALLIATIVE MEDICINE"),
                            ("PLASTIC SURGERY", "PLASTIC SURGERY"),
                            (
                                "PAEDIATRICS AND CHILD HEALTH",
                                "PAEDIATRICS AND CHILD HEALTH",
                            ),
                            ("ANAESTHESIA", "ANAESTHESIA"),
                            ("CARDIOLOGIST", "CARDIOLOGIST"),
                            ("UROLOGIST", "UROLOGIST"),
                            ("PSYCHOLOGIST", "PSYCHOLOGIST"),
                            ("PHYSIOTHERAPIST", "PHYSIOTHERAPIST"),
                            ("FUNCTIONAL MEDICINE", "FUNCTIONAL MEDICINE"),
                            ("CARDIOTHORACIC SURGEON", "CARDIOTHORACIC SURGEON"),
                            ("HIV/AIDS SPECIALIST", "HIV/AIDS SPECIALIST"),
                            ("FAMILY THERAPIST", "FAMILY THERAPIST"),
                            ("PATHOLOGY", "PATHOLOGY"),
                            ("NUTRITIONIST", "NUTRITIONIST"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_person",
                        to="common.person",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
