# Generated by Django 4.2.1 on 2023-12-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0019_practitioner"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="personattachment",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="personcontact",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="personid",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="practitioner",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="relatedperson",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="orgunit_type",
            field=models.CharField(
                choices=[
                    ("cluster", "Cluster"),
                    ("branch", "Branch"),
                    ("dept", "Department"),
                ],
                max_length=255,
            ),
        ),
    ]
