# Generated by Django 4.2.1 on 2023-12-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0020_person_cluster_id_personattachment_cluster_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="created_by",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="updated_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationtransitionlog",
            name="created_by",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="organisationtransitionlog",
            name="updated_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="created_by",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="updated_by",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
