# Generated by Django 4.2.1 on 2024-01-16 14:02

import uuid

import django.db.models.deletion
import sil_transitions.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0022_alter_practitioner_qualification"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationOnboarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Organisation information has not yet been submitted (default at registration).",
                            ),
                            (
                                "REVIEWING",
                                "Organisation information has been submitted and is being reviewed.",
                            ),
                            (
                                "ACCEPTED",
                                "Organisation information has been reviewed and verified as true. The organization can now use advantage.",
                            ),
                            (
                                "REJECTED",
                                "Organisation information has been reviewed and verified as false. Organization is thus rejected.",
                            ),
                        ],
                        default="PENDING",
                        max_length=255,
                    ),
                ),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="org_verification_status",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(models.Model, sil_transitions.mixins.TransitionAndLogMixin),
        ),
        migrations.CreateModel(
            name="OrganisationOnboardingTransitionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Organisation information has not yet been submitted (default at registration).",
                            ),
                            (
                                "REVIEWING",
                                "Organisation information has been submitted and is being reviewed.",
                            ),
                            (
                                "ACCEPTED",
                                "Organisation information has been reviewed and verified as true. The organization can now use advantage.",
                            ),
                            (
                                "REJECTED",
                                "Organisation information has been reviewed and verified as false. Organization is thus rejected.",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_from",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Organisation information has not yet been submitted (default at registration).",
                            ),
                            (
                                "REVIEWING",
                                "Organisation information has been submitted and is being reviewed.",
                            ),
                            (
                                "ACCEPTED",
                                "Organisation information has been reviewed and verified as true. The organization can now use advantage.",
                            ),
                            (
                                "REJECTED",
                                "Organisation information has been reviewed and verified as false. Organization is thus rejected.",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_to",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Organisation information has not yet been submitted (default at registration).",
                            ),
                            (
                                "REVIEWING",
                                "Organisation information has been submitted and is being reviewed.",
                            ),
                            (
                                "ACCEPTED",
                                "Organisation information has been reviewed and verified as true. The organization can now use advantage.",
                            ),
                            (
                                "REJECTED",
                                "Organisation information has been reviewed and verified as false. Organization is thus rejected.",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_transition_logs",
                        to="common.organisationonboarding",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
        ),
    ]
