# Generated by Django 4.2.1 on 2024-01-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0023_organisationonboarding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationonboarding",
            name="onboarding_session_level",
            field=models.CharField(
                choices=[
                    (
                        "INTERESTS",
                        "Provider has been registered or regestration has been accepeted.The discovery of provider's motive(s).(default transition step upon signing-in is interest).",
                    ),
                    (
                        "BASIC DETAILS",
                        "Provider interest has been submitted and collection of their primary information it being done.",
                    ),
                    (
                        "BUSINESS DETAILS",
                        "Provider basic details has been submitted and their primary business information has to be submitted.",
                    ),
                    (
                        "FACILITY DETAILS",
                        "Provider core primary information has been done and their working premises has to be confirmed and verified.",
                    ),
                    (
                        "TERMS AND CONDITIONS",
                        "Provider existence and operation has been attested thus proceed to establishment of a legally biding contract.They have both personal and legal right to vow or disavow.",
                    ),
                    (
                        "FINAL REVIEW AND SUBMISSION",
                        "Provider has vowed the terms and conditions and proceeds to attest all their details for the ultimate lodgement.",
                    ),
                ],
                default="INTERESTS",
                max_length=255,
            ),
        ),
    ]
