# Generated by Django 4.2.1 on 2024-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0025_alter_organisationonboarding_onboarding_session_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationonboarding",
            name="branch_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationonboarding",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationonboarding",
            name="department_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationonboarding",
            name="preferences",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="organisationonboarding",
            name="workstation_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
