# Generated by Django 4.2.1 on 2024-01-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0026_organisationonboarding_branch_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationonboarding",
            name="organisation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="onboarding",
                to="common.organisation",
            ),
        ),
    ]
