# Generated by Django 4.2.1 on 2024-02-27 12:46

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import sil_advantage.common.models.common_models
import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_alter_practitioner_qualification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image/png", "PNG"),
                            ("image/jpeg", "JPEG"),
                            ("application/pdf", "PDF"),
                            ("application/vnd.ms-excel", "xlsx"),
                            ("application/msword", "doc"),
                            (
                                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                "docx",
                            ),
                            (
                                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                "xlsx",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "data",
                    models.FileField(
                        max_length=255,
                        upload_to=sil_advantage.common.models.common_models.get_directory,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "size",
                    models.IntegerField(
                        help_text="The size of the attachment in bytes"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "aspect_ratio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("file_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
