# Generated by Django 4.2.1 on 2024-03-05 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0027_alter_organisationonboarding_organisation"),
        ("common", "0030_attachment"),
    ]

    operations = []
