# Generated by Django 4.2.1 on 2024-03-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0031_merge_20240305_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
