# Generated by Django 4.2.1 on 2024-04-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0032_person_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personid",
            name="id_document_type",
            field=models.CharField(
                choices=[
                    ("alienID", "Alien ID"),
                    ("militaryID", "Military ID"),
                    ("nationalID", "National ID"),
                    ("passportID", "Passport Number"),
                    ("kraPIN", "KRA PIN"),
                    ("payerID", "Payer ID"),
                ],
                max_length=255,
            ),
        ),
    ]
