# Generated by Django 4.2.1 on 2024-05-29 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0035_consent_consenttransitionlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consenttransitionlog",
            name="status",
        ),
        migrations.RemoveField(
            model_name="personotp",
            name="is_used",
        ),
    ]
