# Generated by Django 4.2.1 on 2024-06-06 10:17

from django.db import migrations, models

import sil_advantage.common.utilities.misc


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0036_remove_consenttransitionlog_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personotp",
            name="code",
            field=models.CharField(
                db_index=True,
                default=sil_advantage.common.utilities.misc.generate_otp,
                max_length=8,
            ),
        ),
    ]
