# Generated by Django 4.2.1 on 2024-07-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0038_alter_practitioner_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consent",
            name="verification_type",
            field=models.CharField(
                choices=[("OTP", "OTP"), ("HUMAN", "Human"), ("USSD", "USSD")],
                max_length=16,
            ),
        ),
    ]
