# Generated by Django 4.2.1 on 2024-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0039_alter_consent_verification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("fr", "French"), ("sw", "Swahili")],
                max_length=4,
                null=True,
            ),
        ),
    ]
