# Generated by Django 4.2.1 on 2024-08-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0041_operatingregion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatingregion",
            name="heirachy_structure",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
