# Generated by Django 4.2.1 on 2024-08-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0042_alter_operatingregion_heirachy_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="associated_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operating_region",
                to="common.operatingregion",
            ),
        ),
    ]
