# Generated by Django 4.2.1 on 2024-08-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_person_associated_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatingregion",
            name="unit_type",
            field=models.CharField(
                choices=[("COUNTY", "COUNTY"), ("SUB_COUNTY", "SUB_COUNTY")],
                max_length=255,
            ),
        ),
    ]
