# Generated by Django 4.2.1 on 2024-08-16 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0044_alter_operatingregion_unit_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="operatingregion",
            unique_together={("name", "unit_type", "organisation")},
        ),
    ]
