# Generated by Django 4.2.1 on 2024-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0044_alter_operatingregion_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personcontact",
            name="contact",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
