# Generated by Django 4.2.1 on 2024-08-16 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0045_alter_operatingregion_unique_together"),
        ("common", "0045_alter_personcontact_contact"),
    ]

    operations = []
