# Generated by Django 4.2.1 on 2024-08-21 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0046_merge_20240816_1648"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consent",
            options={"ordering": ("-updated", "-created")},
        ),
        migrations.AlterUniqueTogether(
            name="consent",
            unique_together={("person", "consent_type")},
        ),
    ]
