# Generated by Django 4.2.1 on 2023-09-15 05:58

import uuid

import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import sil_advantage.common.models.mixins
import sil_advantage.integrations.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("visits", "0001_squashed_0018_alter_visit_post_visit_survey_token"),
        ("common", "0001_squashed_0016_instancehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "sales_invoice_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        default="DRAFT",
                        max_length=255,
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "service_request",
                    models.OneToOneField(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="visits.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.integrations.mixins.RemoteObjectMixin,
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ClinicalOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "sales_order_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        default="DRAFT",
                        max_length=255,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "service_request",
                    models.OneToOneField(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_order",
                        to="visits.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.integrations.mixins.RemoteObjectMixin,
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ClinicalOrderTransitionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "workflow_state_from",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "workflow_state_to",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "clinical_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_transition_logs",
                        to="billing.clinicalorder",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="InvoiceTransitionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "workflow_state_from",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "workflow_state_to",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_transition_logs",
                        to="billing.invoice",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("payment_receipt_id", models.UUIDField(unique=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=20,
                    ),
                ),
                ("currency", models.UUIDField(default=0)),
                (
                    "customer_invoice_payment_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("payment_method", models.UUIDField(default=0)),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        default="DRAFT",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PaymentTransitionLog",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "workflow_state_from",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "workflow_state_to",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_transition_logs",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="BillableItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("product_id", models.UUIDField()),
                (
                    "sales_order_line_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "sales_invoice_line_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "clinical_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="billing.clinicalorder",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="billing.invoice",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(default="Item Name", max_length=255)),
                ("pricelist_product_id", models.UUIDField(default=0)),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=20,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.integrations.mixins.RemoteObjectMixin,
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "sales_credit_note_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "refund_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("reason", models.TextField(max_length=255)),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        default="DRAFT",
                        max_length=255,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="billing.invoice",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.integrations.mixins.RemoteObjectMixin,
                sil_advantage.common.models.mixins.TransitionValidationMixin,
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RefundTransitionLog",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "workflow_state_from",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "workflow_state_to",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Editable by document creator."),
                            ("SUBMITTED", "Submitted for review by approver(s)"),
                            ("RETURNED", "Returned to creator to make corretions."),
                            ("PROCESSED", "Been approved and accounting entries made."),
                            ("REJECTED", "Rejected by approver(s)"),
                            ("INVALIDATED", "Cancelled for editing in a new document."),
                            ("ARCHIVED", "Closed for an processed document."),
                            ("CLOSED", "Closed for a document that is not processed."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_transition_logs",
                        to="billing.refund",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RefundLine",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "sales_credit_note_line_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_line",
                        to="billing.billableitem",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_lines",
                        to="billing.refund",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.integrations.mixins.RemoteObjectMixin,
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
