# Generated by Django 4.2.1 on 2023-09-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_squashed_0018_alter_visit_post_visit_survey_token"),
        ("billing", "0001_squashed_0019_refund_refundtransitionlog_refundline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billableitem",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="billableitem",
            name="original_price",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name="billableitem",
            name="price",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name="billableitem",
            name="pricelist_product_id",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="clinicalorder",
            name="service_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clinical_order",
                to="visits.servicerequest",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="service_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="visits.servicerequest",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.UUIDField(),
        ),
    ]
