# Generated by Django 4.2.1 on 2023-12-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0020_alter_billableitem_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billableitem",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalorder",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicalordertransitionlog",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="invoicetransitionlog",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransitionlog",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="refund",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="refundline",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="refundtransitionlog",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
