# Generated by Django 4.2.1 on 2024-02-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0023_alter_billableitem_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
