# Generated by Django 4.2.1 on 2024-03-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0024_payment_payment_method_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "SELF_PAY",
                        "To be paid by patient to cover for costs not undertaken by the guarantor",
                    ),
                    (
                        "COPAY",
                        "To be paid by patient as obligation requested from the guarantor",
                    ),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
