# Generated by Django 4.2.1 on 2024-04-19 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0025_payment_payment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billableitem",
            options={"ordering": ("updated", "created")},
        ),
    ]
