# Generated by Django 4.2.1 on 2024-05-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0027_refund_kra_reason_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="kra_reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Missing Quantity"),
                    ("02", "Missing Item"),
                    ("03", "Damaged"),
                    ("04", "Wasted"),
                    ("05", "Raw Material Shortage"),
                    ("06", "Refund"),
                    ("07", "Wrong Customer PIN"),
                    ("08", "Wrong Customer name"),
                    ("09", "Wrong Amount/price"),
                    ("10", "Wrong Quantity"),
                    ("11", "Wrong Item(s)"),
                    ("12", "Wrong tax type"),
                    ("13", "Other reason"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
