# Generated by Django 4.2.1 on 2024-06-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0028_alter_refund_kra_reason_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="billableitem",
            name="tax_rate",
            field=models.CharField(blank=True, null=True),
        ),
    ]
