# Generated by Django 4.2.1 on 2024-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0029_billableitem_tax_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundline",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
