# Generated by Django 4.2.1 on 2024-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0030_refundline_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalorder",
            name="sales_order_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
