# Generated by Django 4.2.1 on 2024-07-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0038_alter_practitioner_qualification"),
        ("billing", "0031_clinicalorder_sales_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalorder",
            name="sales_order_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="refund",
            name="refund_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="clinicalorder",
            unique_together={("organisation", "sales_order_number")},
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("organisation", "invoice_number")},
        ),
        migrations.AlterUniqueTogether(
            name="refund",
            unique_together={("organisation", "refund_number")},
        ),
    ]
