# Generated by Django 4.2.1 on 2024-10-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0032_alter_clinicalorder_sales_order_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
