# Generated by Django 4.2.1 on 2023-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_squashed_0004_alter_organisationsetting_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationsetting",
            name="preference",
            field=models.JSONField(),
        ),
    ]
