# Generated by Django 4.2.1 on 2024-04-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0007_alter_organisationsetting_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationsetting",
            name="branch_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationsetting",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationsetting",
            name="department_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationsetting",
            name="workstation_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
