# Generated by Django 4.2.1 on 2024-05-16 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0033_alter_personid_id_document_type"),
        ("settings", "0008_organisationsetting_branch_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organisationsetting",
            unique_together={("name", "organisation", "branch_id")},
        ),
    ]
