# Generated by Django 4.2.1 on 2024-06-04 08:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0036_remove_consenttransitionlog_status_and_more"),
        ("sil_auth", "0001_squashed_0004_siluser_matrix_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SILUserMFA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "mfa_type",
                    models.CharField(
                        choices=[("PHONE_OTP", "Phone OTP")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ENABLED", "Enabled"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "otp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="common.personotp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mfa_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
