# Generated by Django 4.2.1 on 2024-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sil_auth", "0005_silusermfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="silusermfa",
            name="secret_key",
            field=models.CharField(
                blank=True,
                help_text="\n        A unique token essential for implementing two-factor authentication\n        using authenticator apps.\n        ",
                max_length=48,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="silusermfa",
            name="mfa_type",
            field=models.CharField(
                choices=[("PHONE_OTP", "Phone OTP"), ("TOTP", "Time-Based OTP")],
                max_length=16,
            ),
        ),
    ]
