# Generated by Django 4.2.1 on 2024-11-08 11:45

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins
import sil_advantage.integrations.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0027_alter_patientlistupload_process_state"),
        ("common", "0047_alter_consent_options_alter_consent_unique_together"),
        ("visits", "0029_rename_scheme_id_visit_patient_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("COMPLETED", "Completed")],
                        default="ACTIVE",
                    ),
                ),
                ("medication_name", models.CharField(max_length=250)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="visits.queue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                sil_advantage.integrations.mixins.RemoteObjectMixin,
                sil_advantage.common.models.mixins.TransitionValidationMixin,
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PrescriptionTransitionLogStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("COMPLETED", "Completed")],
                        max_length=250,
                    ),
                ),
                (
                    "status_from",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("COMPLETED", "Completed")],
                        max_length=250,
                    ),
                ),
                (
                    "status_to",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("COMPLETED", "Completed")],
                        max_length=250,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescription_transition_logs",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Dosage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.CharField(blank=True, max_length=255, null=True)),
                ("dose_quantity", models.FloatField(blank=True, null=True)),
                ("dose_unit", models.CharField(blank=True, max_length=50, null=True)),
                ("period", models.CharField(blank=True, max_length=50, null=True)),
                ("period_unit", models.CharField(blank=True, max_length=50, null=True)),
                ("frequency", models.CharField(blank=True, max_length=50, null=True)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "duration_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("condition", models.CharField(blank=True, max_length=255, null=True)),
                ("patient_instruction", models.TextField(blank=True, null=True)),
                ("additional_instruction", models.JSONField(blank=True, null=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        max_length=250,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dosages",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
        ),
    ]
