# Generated by Django 4.2.1 on 2024-11-11 07:45

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0047_alter_consent_options_alter_consent_unique_together"),
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DosageInstruction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("route", models.CharField(blank=True, max_length=255, null=True)),
                ("dose_quantity", models.FloatField(blank=True, null=True)),
                ("dose_unit", models.CharField(blank=True, max_length=50, null=True)),
                ("period", models.CharField(blank=True, max_length=50, null=True)),
                ("period_unit", models.CharField(blank=True, max_length=50, null=True)),
                ("frequency", models.CharField(blank=True, max_length=50, null=True)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "duration_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("condition", models.CharField(blank=True, max_length=255, null=True)),
                ("patient_instruction", models.TextField(blank=True, null=True)),
                ("additional_instruction", models.JSONField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        max_length=250,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dosages",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.DeleteModel(
            name="Dosage",
        ),
    ]
