# Generated by Django 4.2.1 on 2024-11-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptions", "0002_dosageinstruction_delete_dosage"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="medication_request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dosageinstruction",
            name="frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
