# Generated by Django 4.2.1 on 2023-09-19 08:43

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import sil_advantage.common.models.common_models
import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_squashed_0016_instancehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("deceased", models.BooleanField(blank=True, default=False)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_person",
                        to="common.person",
                    ),
                ),
                ("customer_id", models.UUIDField(blank=True, null=True)),
                (
                    "file_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "global_health_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The patient's global identifier issued by health CRM.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("clinical_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
                "unique_together": {("file_number", "organisation")},
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image/png", "PNG"),
                            ("image/jpeg", "JPEG"),
                            ("application/pdf", "PDF"),
                            ("application/vnd.ms-excel", "xlsx"),
                            ("application/msword", "doc"),
                            (
                                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                "docx",
                            ),
                            (
                                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                "xlsx",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "data",
                    models.FileField(
                        max_length=255,
                        upload_to=sil_advantage.common.models.common_models.get_directory,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "size",
                    models.IntegerField(
                        help_text="The size of the attachment in bytes"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "aspect_ratio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CLINICAL_NOTES", "CLINICAL_NOTES"),
                            ("DISCHARGE_SUMMARY", "DISCHARGE_SUMMARY"),
                            ("FINAL_BILL", "FINAL_BILL"),
                            ("INTERIM_BILL", "INTERIM_BILL"),
                            ("LAB_RESULTS", "LAB_RESULTS"),
                            ("MEDICAL_REPORT", "MEDICAL_REPORT"),
                            ("PRE_AUTHORIZATION_FORM", "PRE_AUTHORIZATION_FORM"),
                            ("PRESCRIPTION", "PRESCRIPTION"),
                            ("PROCEDURE_RESULTS", "PROCEDURE_RESULTS"),
                            ("RADIOLOGY_RESULTS", "RADIOLOGY_RESULTS"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=100,
                    ),
                ),
                ("visit_date", models.DateField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_document",
                        to="patients.patient",
                    ),
                ),
                ("document_number", models.CharField(blank=True, null=True)),
                (
                    "file_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("ARCHIVED", "ARCHIVED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DocumentTransitionLog",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "document_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("ARCHIVED", "ARCHIVED"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document_status_from",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("ARCHIVED", "ARCHIVED"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document_status_to",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("ARCHIVED", "ARCHIVED"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transition_date", models.DateField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_transition_logs",
                        to="patients.patientdocument",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
