# Generated by Django 4.2.1 on 2023-10-26 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "patients",
            "0001_squashed_0014_remove_patient_registration_complete_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="deceased",
        ),
    ]
