# Generated by Django 4.2.1 on 2023-12-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0015_remove_patient_deceased"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttransitionlog",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
