# Generated by Django 4.2.1 on 2024-02-28 13:33

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0030_attachment"),
        ("patients", "0018_alter_documenttransitionlog_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientListUpload",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("success_count", models.IntegerField(default=0)),
                ("fail_count", models.IntegerField(default=0)),
                (
                    "process_state",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("COMPLETE", "COMPLETE"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "failed_uploads_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="common.attachment",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "upload_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="common.attachment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
