# Generated by Django 4.2.1 on 2024-03-06 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0031_merge_20240305_1131"),
        ("patients", "0019_patientlistupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientlistupload",
            name="mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The user-defined excel column mappings",
            ),
        ),
        migrations.AlterField(
            model_name="patientlistupload",
            name="failed_uploads_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="common.attachment",
            ),
        ),
    ]
