# Generated by Django 4.2.1 on 2024-03-21 07:02

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0032_person_metadata"),
        ("patients", "0020_patientlistupload_mapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientCover",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("scheme_name", models.CharField(max_length=255)),
                ("scheme_id", models.UUIDField(blank=True, null=True)),
                ("payer_id", models.UUIDField(blank=True, null=True)),
                ("member_number", models.CharField(max_length=60)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_principal", models.BooleanField(blank=True, default=False)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_covers",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
                "unique_together": {("patient", "scheme_id")},
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
