# Generated by Django 4.2.1 on 2024-04-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0021_patientcover"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientlistupload",
            name="upload_type",
            field=models.CharField(
                choices=[("SEGMENT", "SEGMENT"), ("GENERAL", "GENERAL")],
                default="GENERAL",
                max_length=20,
            ),
        ),
    ]
