# Generated by Django 4.2.1 on 2024-05-16 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0022_patientlistupload_upload_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientlistupload",
            options={"ordering": ("-updated", "-created")},
        ),
    ]
