# Generated by Django 4.2.1 on 2024-06-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0023_alter_patientlistupload_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADVANTAGE_USER_REGISTRATION", "ADVANTAGE_USER_REGISTRATION"),
                    ("UPLOAD", "UPLOAD"),
                ],
                default="ADVANTAGE_USER_REGISTRATION",
                max_length=50,
                null=True,
            ),
        ),
    ]
