# Generated by Django 4.2.1 on 2024-07-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0024_patient_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="health_crm_sync_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAILED", "FAILED"),
                ],
                help_text="Indicates the sync status of the patient with Health CRM.",
                max_length=20,
                null=True,
            ),
        ),
    ]
