# Generated by Django 4.2.1 on 2024-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0024_patient_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADVANTAGE_USER_REGISTRATION", "ADVANTAGE_USER_REGISTRATION"),
                    ("UPLOAD", "UPLOAD"),
                    ("USSD_SELF_ENROLLMENT", "USSD_SELF_ENROLLMENT"),
                ],
                default="ADVANTAGE_USER_REGISTRATION",
                max_length=50,
                null=True,
            ),
        ),
    ]
