# Generated by Django 4.2.1 on 2024-08-02 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0025_alter_patient_source"),
        ("patients", "0025_patient_health_crm_sync_status"),
    ]

    operations = []
