# Generated by Django 4.2.1 on 2024-09-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0026_merge_20240802_0937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientlistupload",
            name="process_state",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("COMPLETE", "COMPLETE"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
