# Generated by Django 4.2.1 on 2024-11-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0027_alter_patientlistupload_process_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
