"""Visits app."""
DRAFT = "DRAFT"
SUBMITTED = "SUBMITTED"
PROCESSED = "PROCESSED"
CLOSED = "CLOSED"

SHORTCUTS = {
    "DRAFT_ONLY": [DRAFT],
    "DRAFT_SUBMIT": [DRAFT, SUBMITTED],
    "DRAFT_SUBMIT_APPROVE": [DRAFT, SUBMITTED, PROCESSED],
    "DRAFT_CLOSED": [DRAFT, CLOSED],
    "SUBMITTED_CLOSED": [DRAFT, SUBMITTED, CLOSED],
}
