# Generated by Django 4.2.1 on 2024-02-16 07:56

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import sil_advantage.common.models.mixins
import sil_advantage.segments.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0028_alter_instancehistory_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("ACTIVE", "ACTIVE"),
                            ("RETIRED", "RETIRED"),
                        ],
                        default="DRAFT",
                        max_length=64,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CERVICAL_CANCER_TIPS", "Cervical Cancer General Tips"),
                            (
                                "CERVICAL_CANCER_HIGH_RISK",
                                "High Risk of Cervical Cancer",
                            ),
                            ("CERVICAL_CANCER_LOW_RISK", "Low Risk of Cervical Cancer"),
                            (
                                "CERVICAL_CANCER_POSITIVE",
                                "Positive for Cervical Cancer",
                            ),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        help_text="stores characteristics of a segment as defined by the user.",
                        null=True,
                        validators=[
                            sil_advantage.segments.models.validate_segment_attributes
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SegmentMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("RETIRED", "RETIRED"),
                        ],
                        default="DRAFT",
                        max_length=64,
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.person"
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="segments.segment",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="members",
            field=models.ManyToManyField(
                related_name="segments",
                through="segments.SegmentMember",
                to="common.person",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="common.organisation",
            ),
        ),
    ]
