# Generated by Django 4.2.1 on 2024-02-19 14:04

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0028_alter_instancehistory_created_by_and_more"),
        ("segments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("name", models.CharField(max_length=128)),
                ("template", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[("SEQUENCED", "SEQUENCED"), ("BLAST", "BLAST")],
                        max_length=64,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "parent",
                    models.OneToOneField(
                        blank=True,
                        help_text="\n        Keeps track of the next message in a sequence.\n        First message has no parent while subsequent messages\n        have a parent based on the sequence.\n        ",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child",
                        to="segments.messagetemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SegmentMessageDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_messages",
                        to="segments.segmentmember",
                    ),
                ),
                (
                    "message_template",
                    models.ForeignKey(
                        help_text="\n        Template used to generate the message.\n        ",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="segments.messagetemplate",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SegmentMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[("SCHEDULED", "SCHEDULED"), ("SENT", "SENT")],
                        default="SCHEDULED",
                        max_length=64,
                    ),
                ),
                (
                    "sequence_interval",
                    models.CharField(
                        help_text="\n        Holds the sequencing interval to send messages.\n        Specifies units of time of when to send an sms i.e minute, hour,\n        day_of_week, day_of_month, month_of_year.\n        Follows the crontab format using a dict to store the args\n        Example:\n        A sequential message sent out on wednesday every week\n        ",
                        max_length=128,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="segments.segment",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="segments.messagetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="messages",
            field=models.ManyToManyField(
                related_name="segments",
                through="segments.SegmentMessage",
                to="segments.messagetemplate",
            ),
        ),
    ]
