# Generated by Django 4.2.1 on 2024-02-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0030_attachment"),
        ("segments", "0002_messagetemplate_segmentmessagedelivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentmember",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_memberships",
                to="common.person",
            ),
        ),
        migrations.AlterField(
            model_name="segmentmember",
            name="segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_memberships",
                to="segments.segment",
            ),
        ),
    ]
