# Generated by Django 4.2.1 on 2024-03-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("segments", "0003_alter_segmentmember_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentmessage",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("INSTANT", "INSTANT"),
                    ("SCHEDULED_ONE_TIME", "SCHEDULED_ONE_TIME"),
                    ("SCHEDULED_RECURRENT", "SCHEDULED_RECURRENT"),
                ],
                default="INSTANT",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segmentmessage",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a scheduled one time message should be sent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="segmentmessage",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AddField(
            model_name="segmentmessagedelivery",
            name="sequence_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="segments.messagetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="message_type",
            field=models.CharField(
                choices=[("SEQUENCED", "SEQUENCED"), ("SINGULAR", "SINGULAR")],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="name",
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name="segment",
            name="name",
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name="segmentmessage",
            name="sequence_interval",
            field=models.CharField(
                blank=True,
                help_text="\n        Holds the sequencing interval to send scheduled recurrent messages.\n        Specifies units of time of when to send an sms i.e minute, hour,\n        day_of_week, day_of_month, month_of_year.\n        Follows the crontab format using a dict to store the args\n        Example:\n        A sequential message sent out on wednesday every week\n        ",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="segmentmessage",
            unique_together={("template", "segment")},
        ),
        migrations.RemoveField(
            model_name="segmentmessage",
            name="delivery_status",
        ),
    ]
