# Generated by Django 4.2.1 on 2024-03-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0032_person_metadata"),
        ("segments", "0004_segmentmessage_delivery_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CERVICAL_CANCER_TIPS", "Cervical Cancer General Tips"),
                    ("CERVICAL_CANCER_HIGH_RISK", "High Risk of Cervical Cancer"),
                    ("CERVICAL_CANCER_LOW_RISK", "Low Risk of Cervical Cancer"),
                    ("CERVICAL_CANCER_POSITIVE", "Positive for Cervical Cancer"),
                    ("BREAST_CANCER_TIPS", "Breast Cancer General Tips"),
                    ("BREAST_CANCER_HIGH_RISK", "High Risk of Breast Cancer"),
                    ("BREAST_CANCER_LOW_RISK", "Low Risk of Breast Cancer"),
                    ("BREAST_CANCER_POSITIVE", "Positive for Breast Cancer"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="segmentmember",
            unique_together={("person", "segment")},
        ),
    ]
