# Generated by Django 4.2.1 on 2024-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0005_alter_segment_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CERVICAL_CANCER_TIPS", "Cervical Cancer General Tips"),
                    ("CERVICAL_CANCER_HIGH_RISK", "High Risk of Cervical Cancer"),
                    ("CERVICAL_CANCER_LOW_RISK", "Low Risk of Cervical Cancer"),
                    ("CERVICAL_CANCER_POSITIVE", "Positive for Cervical Cancer"),
                    ("BREAST_CANCER_TIPS", "Breast Cancer General Tips"),
                    ("BREAST_CANCER_HIGH_RISK", "High Risk of Breast Cancer"),
                    ("BREAST_CANCER_LOW_RISK", "Low Risk of Breast Cancer"),
                    ("BREAST_CANCER_POSITIVE", "Positive for Breast Cancer"),
                    ("BREAST_CANCER_AVERAGE_RISK", "Average Risk of Breast Cancer"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
