# Generated by Django 4.2.1 on 2024-04-11 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_senderid"),
        ("segments", "0006_alter_segment_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="notifications.senderid",
            ),
        ),
    ]
