# Generated by Django 4.2.1 on 2024-04-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0007_segmentmessage_sender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="segmentmessagedelivery",
            options={},
        ),
        migrations.AddField(
            model_name="segmentmessagedelivery",
            name="branch_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="segmentmessagedelivery",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="segmentmessagedelivery",
            name="department_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="segmentmessagedelivery",
            name="workstation_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
