# Generated by Django 4.2.1 on 2024-05-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_sms"),
        ("segments", "0008_alter_segmentmessagedelivery_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentmessagedelivery",
            name="sms",
            field=models.ForeignKey(
                blank=True,
                help_text="\n        Holds a reference of the SMS that will be used to track\n        real-time delivery statuses.\n        ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="notifications.sms",
            ),
        ),
    ]
