# Generated by Django 4.2.1 on 2024-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0009_segmentmessagedelivery_sms"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentmember",
            name="branch_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="segmentmember",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="segmentmember",
            name="department_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="segmentmember",
            name="workstation_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
