# Generated by Django 4.2.1 on 2024-05-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0010_segmentmember_branch_id_segmentmember_cluster_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagetemplate",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="segments.messagetemplate",
                verbose_name="parent",
            ),
        ),
    ]
