# Generated by Django 4.2.1 on 2024-05-29 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0011_alter_messagetemplate_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagetemplate",
            options={"ordering": ("-updated", "-created")},
        ),
        migrations.AlterModelOptions(
            name="segment",
            options={"ordering": ("-updated", "-created")},
        ),
        migrations.AlterModelOptions(
            name="segmentmessagedelivery",
            options={"ordering": ("-updated", "-created")},
        ),
    ]
