# Generated by Django 4.2.1 on 2024-07-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "segments",
            "0012_alter_messagetemplate_options_alter_segment_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentmember",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UPLOAD", "Members added via file upload"),
                    ("MANUAL", "Members added manually"),
                    ("AUTOMATIC", "Members added via filters"),
                ],
                default="MANUAL",
                max_length=50,
                null=True,
            ),
        ),
    ]
