# Generated by Django 4.2.1 on 2024-07-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0013_segmentmember_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentmessage",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("INSTANT", "Sends message immediately"),
                    ("SCHEDULED_ONE_TIME", "Sends a scheduled message once"),
                    ("SCHEDULED_RECURRENT", "Sends a scheduled message recurrently"),
                ],
                max_length=64,
            ),
        ),
    ]
