# Generated by Django 4.2.1 on 2024-07-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0015_segmentupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="send_welcome_message_notification",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="segment",
            name="welcome_message_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_welcome_messages",
                to="segments.messagetemplate",
            ),
        ),
    ]
