# Generated by Django 4.2.1 on 2024-07-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0016_segment_send_welcome_message_notification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentmember",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UPLOAD", "Members added via file upload"),
                    ("MANUAL", "Members added manually"),
                    ("AUTOMATIC", "Members added via filters"),
                    ("USSD", "Members added via USSD"),
                ],
                default="MANUAL",
                max_length=50,
                null=True,
            ),
        ),
    ]
