# Generated by Django 4.2.1 on 2024-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0017_alter_segmentmember_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Message in draft state"),
                    ("ACTIVE", "Message in active state"),
                    ("RETIRED", "Message in retired state"),
                ],
                default="DRAFT",
                max_length=64,
            ),
        ),
    ]
