# Generated by Django 4.2.1 on 2024-07-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0017_alter_segmentmember_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="template_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="template_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="template_sw",
            field=models.TextField(null=True),
        ),
    ]
