# Generated by Django 4.2.1 on 2024-07-25 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0018_messagetemplate_status"),
        ("segments", "0018_messagetemplate_template_en_and_more"),
    ]

    operations = []
