# Generated by Django 4.2.1 on 2024-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0019_merge_20240725_1627"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("ACTIVE", "ACTIVE"),
                    ("RETIRED", "RETIRED"),
                ],
                default="ACTIVE",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="segmentmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("RETIRED", "RETIRED"),
                ],
                default="CONFIRMED",
                max_length=64,
            ),
        ),
    ]
