# Generated by Django 4.2.1 on 2024-08-02 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0020_alter_segment_status_alter_segmentmember_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="segmentmessage",
            unique_together=set(),
        ),
    ]
