# Generated by Django 4.2.1 on 2024-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0021_alter_segmentmessage_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("INSTANT", "Instant message."),
                    ("GENERAL", "General message."),
                ],
                default="GENERAL",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("SEQUENCED", "A sequenced message template."),
                    ("SINGULAR", "A standalone message"),
                ],
                max_length=64,
            ),
        ),
    ]
