# Generated by Django 4.2.1 on 2024-08-09 08:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0022_messagetemplate_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentmember",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                help_text="stores extra information related to a segment member.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="segmentupload",
            name="extra_headers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
