# Generated by Django 4.2.1 on 2024-08-13 12:53

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_person_associated_region"),
        ("segments", "0023_segmentmember_extra_data_segmentupload_extra_headers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CLINICAL", "Clinical"),
                            ("ADVANTAGE", "Advantage"),
                            ("ERP", "ERP"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "allowed_operations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64), size=None
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("CLOSE_ENDED", "Close Ended"),
                            ("OPEN_ENDED", "Open Ended"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "value_data_type",
                    models.CharField(
                        choices=[
                            ("NUMBER", "Number"),
                            ("STRING", "String"),
                            ("DATE", "Date"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "choice_source",
                    models.CharField(
                        choices=[
                            ("OCL", "OCL"),
                            ("CLOSE_ENDED_CHOICES", "Close Ended Choices"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("DATE_PICKER", "Date Picker"),
                            ("TEXT_INPUT", "Text Input"),
                            ("NUMBER_INPUT", "Number Input"),
                            ("DROPDOWN", "Dropdown"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "close_ended_choices",
                    models.JSONField(
                        blank=True,
                        help_text="stores the choices available for close ended filters.",
                        null=True,
                    ),
                ),
                (
                    "ocl_query_options",
                    models.JSONField(
                        blank=True,
                        help_text="\n        stores the configuration options that help in limiting results\n        to those relevant for a filter when making a request to the OCL instance\n        ",
                        null=True,
                    ),
                ),
                (
                    "cube_config",
                    models.JSONField(
                        blank=True,
                        help_text="\n        stores the configuration options that help\n        in building/making a query meant for cube\n        ",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="FilterGroup",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("name", models.CharField(max_length=50)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="filter_execution_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("CLINIC", "In Progess"),
                    ("FAILED", "Failed"),
                    ("SUCCESS", "Success"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FilterGroupFilter",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("EQUALS", "Equals"),
                            ("GREATER_THAN", "Greater Than"),
                            ("LESS_THAN", "Less Than"),
                            ("LESS_THAN_OR_EQUAL_TO", "Less Than or Equal To"),
                            ("GREATER_THAN_OR_EQUAL_TO", "Greater Than or Equal To"),
                        ],
                        help_text="the operation to be applied to this filter within the group.",
                        max_length=64,
                    ),
                ),
                ("value", models.CharField(max_length=256)),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_groups",
                        to="segments.filter",
                    ),
                ),
                (
                    "filter_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="segments.filtergroup",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="filtergroup",
            name="segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filter_groups",
                to="segments.segment",
            ),
        ),
    ]
