# Generated by Django 4.2.1 on 2024-08-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0044_alter_operatingregion_unit_type"),
        (
            "segments",
            "0024_filter_filtergroup_segment_filter_execution_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentmember",
            name="member_associated_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_operating_region",
                to="common.operatingregion",
            ),
        ),
    ]
