# Generated by Django 4.2.1 on 2024-08-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0025_segmentmember_member_associated_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagetemplate",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
