# Generated by Django 4.2.1 on 2024-08-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0026_alter_messagetemplate_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentmessage",
            name="send_on_segment_join",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the message is be sent when a new member joins.",
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="segmentmessage",
            name="segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_messages",
                to="segments.segment",
            ),
        ),
    ]
