# Generated by Django 4.2.1 on 2024-08-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0027_segmentmessage_send_on_segment_join_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Segment in draft state"),
                    ("ACTIVE", "Segment in active state"),
                    ("RETIRED", "Segment in retired state"),
                ],
                default="ACTIVE",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="segmentmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Member in draft state"),
                    ("CONFIRMED", "Member in confirmed state"),
                    ("RETIRED", "Member in retired state"),
                ],
                default="CONFIRMED",
                max_length=64,
            ),
        ),
    ]
