# Generated by Django 4.2.1 on 2024-08-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0028_alter_segment_status_alter_segmentmember_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="choice_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OCL", "OCL"),
                    ("CLOSE_ENDED_CHOICES", "Close Ended Choices"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
