# Generated by Django 4.2.1 on 2024-08-31 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0029_alter_filter_choice_source"),
        ("segments", "0029_segmenttransitionlog"),
    ]

    operations = []
