# Generated by Django 4.2.1 on 2024-09-02 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0030_merge_20240831_1135"),
        ("segments", "0030_messagetemplatetransitionlog"),
    ]

    operations = []
