# Generated by Django 4.2.1 on 2024-09-03 07:40

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins
import sil_advantage.segments.models.filters


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0047_alter_consent_options_alter_consent_unique_together"),
        ("segments", "0031_merge_20240902_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="close_ended_choices",
            field=models.JSONField(
                blank=True,
                help_text="stores the choices available for close ended filters.",
                null=True,
                validators=[
                    sil_advantage.segments.models.filters.validate_close_ended_choices
                ],
            ),
        ),
        migrations.CreateModel(
            name="SegmentMemberTransitionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("status_to", models.CharField(max_length=16)),
                ("status_from", models.CharField(max_length=16)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "segment_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_member_logs",
                        to="segments.segmentmember",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
