# Generated by Django 4.2.1 on 2024-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0032_alter_filter_close_ended_choices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="filter_execution_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("FAILED", "Failed"),
                    ("SUCCESS", "Success"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
