# Generated by Django 4.2.1 on 2024-09-26 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0034_filterexecutiontransitionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentmessagedelivery",
            name="segment_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_message_deliveries",
                to="segments.segmentmessage",
            ),
        ),
    ]
