# Generated by Django 4.2.1 on 2024-11-08 12:41

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0047_alter_consent_options_alter_consent_unique_together"),
        ("segments", "0035_segmentmessagedelivery_segment_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                ("name", models.CharField(max_length=48)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="classification",
            field=models.CharField(
                choices=[
                    ("JOURNEY", "Segment that belongs to a journey"),
                    (
                        "DYNAMIC",
                        "Automatically update their members based on its criteria",
                    ),
                    (
                        "STATIC",
                        "Add records which meet a set criteria at the point when the list is saved",
                    ),
                ],
                default="STATIC",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="JourneyMember",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Member in active state within journey"),
                            ("RETIRED", "Member in retired state within journey"),
                        ],
                        default="ACTIVE",
                        max_length=64,
                    ),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="segments.segmentmember",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journey_members",
                        to="segments.journey",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journey_memberships",
                        to="common.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="JourneyAttributes",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("EQUALS", "Equals"),
                            ("GREATER_THAN", "Greater Than"),
                            ("LESS_THAN", "Less Than"),
                            ("LESS_THAN_OR_EQUAL_TO", "Less Than or Equal To"),
                            ("GREATER_THAN_OR_EQUAL_TO", "Greater Than or Equal To"),
                        ],
                        help_text="the operation to be applied to this filter within the journey.",
                        max_length=64,
                    ),
                ),
                ("value", models.CharField(max_length=256)),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="segments.filter",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journey_attributes",
                        to="segments.journey",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="JourneySegment",
            fields=[
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("branch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cluster_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField()),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journey_segments",
                        to="segments.journey",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="segments.journeysegment",
                        verbose_name="parent",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="segments.segment",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
                "unique_together": {("journey", "segment")},
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
