# Generated by Django 4.2.1 on 2024-11-11 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0047_alter_consent_options_alter_consent_unique_together"),
        ("segments", "0036_journey_segment_classification_journeymember_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journeymember",
            options={"ordering": ("-updated", "-created")},
        ),
        migrations.AlterUniqueTogether(
            name="journeymember",
            unique_together={("journey", "person")},
        ),
    ]
