# Generated by Django 4.2.1 on 2024-11-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0037_alter_journeymember_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="ussd_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
