# Generated by Django 4.2 on 2023-08-28 09:16

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import sil_advantage.common.models.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_squashed_0016_instancehistory"),
        (
            "patients",
            "0001_squashed_0014_remove_patient_registration_complete_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                ("description", models.TextField(default="")),
                ("slot_duration", models.PositiveSmallIntegerField(default=30)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("OPHTHALMOLOGY", "OPHTHALMOLOGY"),
                            ("INTERNAL MEDICINE", "INTERNAL MEDICINE"),
                            ("CLINICAL PATHOLOGY", "CLINICAL PATHOLOGY"),
                            ("CONSERVATIVE DENTISTRY", "CONSERVATIVE DENTISTRY"),
                            (
                                "GENERAL SURGERY  PLASTIC SURGERY",
                                "GENERAL SURGERY  PLASTIC SURGERY",
                            ),
                            ("MICROBIOLOGY", "MICROBIOLOGY"),
                            ("ORAL PATHOLOGY", "ORAL PATHOLOGY"),
                            (
                                "GENERAL SURGERY  PAEDIATRIC SURGERY",
                                "GENERAL SURGERY  PAEDIATRIC SURGERY",
                            ),
                            (
                                "OBSTETRICS AND GYNAECOLOGY  ONCOLOGY/RADIOTHERAPY",
                                "OBSTETRICS AND GYNAECOLOGY  ONCOLOGY/RADIOTHERAPY",
                            ),
                            ("ENDODONTICS", "ENDODONTICS"),
                            ("RADIOLOGY", "RADIOLOGY"),
                            ("NEPHROLOGY", "NEPHROLOGY"),
                            ("EMERGENCY MEDICINE", "EMERGENCY MEDICINE"),
                            (
                                "EAR  NOSE AND THROAT (ENT SURGERY)",
                                "EAR  NOSE AND THROAT (ENT SURGERY)",
                            ),
                            ("PAEDIATRIC SURGERY", "PAEDIATRIC SURGERY"),
                            ("ONCOLOGY", "ONCOLOGY"),
                            ("PROSTHETIC DENTISTRY", "PROSTHETIC DENTISTRY"),
                            (
                                "OBSTETRICS AND GYNAECOLOGY",
                                "OBSTETRICS AND GYNAECOLOGY",
                            ),
                            ("PUBLIC HEALTH", "PUBLIC HEALTH"),
                            ("OCCUPATIONAL MEDICINE", "OCCUPATIONAL MEDICINE"),
                            ("GENERAL PATHOLOGY", "GENERAL PATHOLOGY"),
                            ("NEUROSURGERY", "NEUROSURGERY"),
                            ("DIABETOLOGY", "DIABETOLOGY"),
                            ("CLINICAL MEDICAL GENETICS", "CLINICAL MEDICAL GENETICS"),
                            ("GENERAL PRACTITIONER", "GENERAL PRACTITIONER"),
                            ("NEUROLOGY", "NEUROLOGY"),
                            ("PROSTHODONTICS", "PROSTHODONTICS"),
                            (
                                "DERMATOLOGY  INTERNAL MEDICINE",
                                "DERMATOLOGY  INTERNAL MEDICINE",
                            ),
                            ("ORTHOPAEDICS", "ORTHOPAEDICS"),
                            ("BIOMATERIALS SCIENCE", "BIOMATERIALS SCIENCE"),
                            (
                                "ORTHOPAEDICS AND TRAUMA SURGERY",
                                "ORTHOPAEDICS AND TRAUMA SURGERY",
                            ),
                            ("RADIOTHERAPY", "RADIOTHERAPY"),
                            ("PAEDIATRIC DENTISTRY", "PAEDIATRIC DENTISTRY"),
                            (
                                "INTERNAL MEDICINE  ONCOLOGY/RADIOTHERAPY",
                                "INTERNAL MEDICINE  ONCOLOGY/RADIOTHERAPY",
                            ),
                            ("ORTHODONTICS", "ORTHODONTICS"),
                            ("RESTORATIVE DENTISTRY", "RESTORATIVE DENTISTRY"),
                            ("GENERAL SURGERY", "GENERAL SURGERY"),
                            (
                                "ORAL AND MAXILLOFACIAL SURGERY",
                                "ORAL AND MAXILLOFACIAL SURGERY",
                            ),
                            ("DERMATOLOGY", "DERMATOLOGY"),
                            ("PSYCHIATRY", "PSYCHIATRY"),
                            (
                                "GENERAL SURGERY  ORTHOPAEDICS",
                                "GENERAL SURGERY  ORTHOPAEDICS",
                            ),
                            ("ORTHOPAEDIC SURGERY", "ORTHOPAEDIC SURGERY"),
                            ("DENTAL RADIOLOGY", "DENTAL RADIOLOGY"),
                            ("PERIODONTOLOGY", "PERIODONTOLOGY"),
                            ("FAMILY MEDICINE", "FAMILY MEDICINE"),
                            ("PALLIATIVE MEDICINE", "PALLIATIVE MEDICINE"),
                            ("PLASTIC SURGERY", "PLASTIC SURGERY"),
                            (
                                "PAEDIATRICS AND CHILD HEALTH",
                                "PAEDIATRICS AND CHILD HEALTH",
                            ),
                            ("ANAESTHESIA", "ANAESTHESIA"),
                            ("CARDIOLOGIST", "CARDIOLOGIST"),
                            ("UROLOGIST", "UROLOGIST"),
                            ("PSYCHOLOGIST", "PSYCHOLOGIST"),
                            ("PHYSIOTHERAPIST", "PHYSIOTHERAPIST"),
                            ("FUNCTIONAL MEDICINE", "FUNCTIONAL MEDICINE"),
                            ("CARDIOTHORACIC SURGEON", "CARDIOTHORACIC SURGEON"),
                            ("HIV/AIDS SPECIALIST", "HIV/AIDS SPECIALIST"),
                            ("FAMILY THERAPIST", "FAMILY THERAPIST"),
                            ("PATHOLOGY", "PATHOLOGY"),
                            ("NUTRITIONIST", "NUTRITIONIST"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "actor",
                    models.CharField(
                        choices=[
                            ("FACILITY", "FACILITY"),
                            ("HEALTHCARE_SERVICE", "HEALTHCARE SERVICE"),
                            ("PRACTITIONER", "PRACTITIONER"),
                        ],
                        default="PRACTITIONER",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "BUSY",
                                "Indicates that the time interval is busy because one or more events have been scheduled for that interval.",
                            ),
                            (
                                "FREE",
                                "Indicates that the time interval is free for scheduling.",
                            ),
                            (
                                "BUSY_TENTATIVE",
                                "Indicates that the time interval is busy because one or more events have been tentatively scheduled for that interval.",
                            ),
                            (
                                "BUSY_UNAVAILABLE",
                                "Indicates that the time interval is busy and that the interval can not be scheduled.",
                            ),
                        ],
                        default="FREE",
                        max_length=255,
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_slots",
                        to="scheduling.schedule",
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ("start",),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            (
                                "BOOKED",
                                "All participant(s) have been considered and the appointment is confirmed to go ahead at the date/times specified.",
                            ),
                            ("CANCELLED", "The appointment has been cancelled."),
                            (
                                "FULFILLED",
                                "This appointment has completed and may have resulted in an encounter.",
                            ),
                            (
                                "NO_SHOW",
                                "Some or all of the participant(s) have not/did not appear for the appointment (usually the patient).",
                            ),
                            (
                                "PENDING",
                                "Some or all of the participant(s) have not finalized their acceptance of the appointment request.",
                            ),
                            (
                                "PROPOSED",
                                "None of the participant(s) have finalized their acceptance of the appointment request, and the start/end time may not be set yet.",
                            ),
                            ("ARRIVED", "Some of the patients have arrived."),
                        ],
                        default="BOOKED",
                        max_length=255,
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slot_appointments",
                        to="scheduling.slot",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pending_reminders",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateTimeField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            (
                                "CHECKUP",
                                "A routine check-up, such as an annual physical",
                            ),
                            ("EMERGENCY", "Emergency appointment"),
                            (
                                "FOLLOWUP",
                                "A follow up visit from a previous appointment",
                            ),
                            ("ROUTINE", "Routine appointment"),
                            ("WALKIN", "A previously unscheduled walk-in visit"),
                        ],
                        default="ROUTINE",
                        max_length=255,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            (
                                "ASAP",
                                "As soon as possible, next highest priority after emergency",
                            ),
                            (
                                "EMERGENCY",
                                "An unforeseen combination of circumstances or the resulting state that calls for immediate action",
                            ),
                            (
                                "PREOP",
                                "Indicates that a service is to be performed prior to a scheduled surgery. When ordering a service and using the pre-op priority, a check is done to see the amount of time that must be allowed for performance of the service.",
                            ),
                            ("ROUTINE", "Routine service, do at usual work hours"),
                        ],
                        default="ROUTINE",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ("-start",),
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="AppointmentTransitionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            (
                                "BOOKED",
                                "All participant(s) have been considered and the appointment is confirmed to go ahead at the date/times specified.",
                            ),
                            ("CANCELLED", "The appointment has been cancelled."),
                            (
                                "FULFILLED",
                                "This appointment has completed and may have resulted in an encounter.",
                            ),
                            (
                                "NO_SHOW",
                                "Some or all of the participant(s) have not/did not appear for the appointment (usually the patient).",
                            ),
                            (
                                "PENDING",
                                "Some or all of the participant(s) have not finalized their acceptance of the appointment request.",
                            ),
                            (
                                "PROPOSED",
                                "None of the participant(s) have finalized their acceptance of the appointment request, and the start/end time may not be set yet.",
                            ),
                            ("ARRIVED", "Some of the patients have arrived."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "appointment_status_from",
                    models.CharField(
                        choices=[
                            (
                                "BOOKED",
                                "All participant(s) have been considered and the appointment is confirmed to go ahead at the date/times specified.",
                            ),
                            ("CANCELLED", "The appointment has been cancelled."),
                            (
                                "FULFILLED",
                                "This appointment has completed and may have resulted in an encounter.",
                            ),
                            (
                                "NO_SHOW",
                                "Some or all of the participant(s) have not/did not appear for the appointment (usually the patient).",
                            ),
                            (
                                "PENDING",
                                "Some or all of the participant(s) have not finalized their acceptance of the appointment request.",
                            ),
                            (
                                "PROPOSED",
                                "None of the participant(s) have finalized their acceptance of the appointment request, and the start/end time may not be set yet.",
                            ),
                            ("ARRIVED", "Some of the patients have arrived."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "appointment_status_to",
                    models.CharField(
                        choices=[
                            (
                                "BOOKED",
                                "All participant(s) have been considered and the appointment is confirmed to go ahead at the date/times specified.",
                            ),
                            ("CANCELLED", "The appointment has been cancelled."),
                            (
                                "FULFILLED",
                                "This appointment has completed and may have resulted in an encounter.",
                            ),
                            (
                                "NO_SHOW",
                                "Some or all of the participant(s) have not/did not appear for the appointment (usually the patient).",
                            ),
                            (
                                "PENDING",
                                "Some or all of the participant(s) have not finalized their acceptance of the appointment request.",
                            ),
                            (
                                "PROPOSED",
                                "None of the participant(s) have finalized their acceptance of the appointment request, and the start/end time may not be set yet.",
                            ),
                            ("ARRIVED", "Some of the patients have arrived."),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_transition_logs",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ScheduleTiming",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("0", "Monday"),
                            ("1", "Tuesday"),
                            ("2", "Wednesday"),
                            ("3", "Thursday"),
                            ("4", "Friday"),
                            ("5", "Saturday"),
                            ("6", "Sunday"),
                        ],
                        max_length=1,
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="common.organisation",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timings",
                        to="scheduling.schedule",
                    ),
                ),
                (
                    "branch_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "department_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workstation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
            },
            bases=(
                sil_advantage.common.models.mixins.ValidationErrorsMixin,
                models.Model,
            ),
        ),
    ]
