# Generated by Django 4.2.1 on 2023-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "scheduling",
            "0001_squashed_0015_alter_appointment_priority_alter_schedule_specialty",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="slot_duration",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
