# Generated by Django 4.2.1 on 2023-11-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0019_practitioner"),
        ("scheduling", "0016_alter_schedule_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="practitioner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="practitioner_schedules",
                to="common.practitioner",
            ),
        ),
    ]
