# Generated by Django 4.2.1 on 2023-12-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0019_alter_schedule_description_alter_schedule_specialty"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="appointmenttransitionlog",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduletiming",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="slot",
            name="cluster_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
