# Generated by Django 4.2.1 on 2024-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0022_update_empty_created_by_and_updated_by_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="updated_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="appointmenttransitionlog",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="appointmenttransitionlog",
            name="updated_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="updated_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="scheduletiming",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="scheduletiming",
            name="updated_by",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="slot",
            name="created_by",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="slot",
            name="updated_by",
            field=models.UUIDField(),
        ),
    ]
